name: Bug report
description: Report a bug or regression
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please include enough detail for maintainers to reproduce and triage in one pass.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - sev-1 (blocks release / production outage)
        - sev-2 (major regression)
        - sev-3 (minor bug)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: User impact
      description: Who is affected and what workflow is blocked?
      placeholder: Describe the impact radius and urgency.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: Describe expected behavior.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happened instead?
      placeholder: Include the observed result or failure.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce it?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, sdetkit version, and anything relevant.
      placeholder: |
        - OS:
        - Python:
        - sdetkit:
        - CI runner (if any):
    validations:
      required: true
