name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List objective conditions for done.
      placeholder: |
        - [ ] Command/UX behavior is documented.
        - [ ] Tests cover the primary and error path.
        - [ ] Backward compatibility is maintained or migration notes are provided.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (critical)
        - P1 (high)
        - P2 (normal)
        - P3 (nice-to-have)
    validations:
      required: true

  - type: input
    id: ownership
    attributes:
      label: Ownership
      description: Who will own or sponsor this request?
      placeholder: "@username or team"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives you've considered?
    validations:
      required: false
