name: sdetkit-github-strict
on:
  pull_request:
  workflow_dispatch:

jobs:
  strict-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -r requirements-test.txt -e .
      - run: python -m pytest -q tests/test_cli_sdetkit.py tests/test_github_actions_quickstart.py tests/test_cli_help_lists_subcommands.py
      - run: python -m sdetkit github-actions-quickstart --format json --strict
      - run: python scripts/check_day15_github_actions_quickstart_contract.py
