name: sdetkit-github-nightly
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  nightly-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -r requirements-test.txt -e .
      - run: python -m sdetkit doctor --format text
      - run: python -m sdetkit repo audit --format json
      - run: python -m sdetkit github-actions-quickstart --execute --evidence-dir docs/artifacts/day15-github-pack/evidence --format json --strict
